const{chromium}=require('playwright'),fs=require('fs');const O={checks:{},details:{},errors:[],overall:'UNKNOWN'},sl=m=>new Promise(r=>setTimeout(r,m));
async function ready(p){await p.waitForFunction(()=>{const l=document.getElementById('loading'),v=document.getElementById('version-pill-home');return l&&getComputedStyle(l).display==='none'&&v&&v.textContent&&!/v—|v-$/.test(v.textContent)},null,{timeout:120000});await p.evaluate(()=>{const o=document.getElementById('onboarding-overlay');if(o&&getComputedStyle(o).display!=='none')finishOnboarding()})}
(async()=>{const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await c.newPage();p.on('pageerror',e=>O.errors.push('page:'+String(e)));p.on('console',m=>{if(m.type()==='error')O.errors.push('console:'+m.text())});
try{
 await p.goto('http://127.0.0.1:8217/?wip='+Date.now(),{waitUntil:'domcontentloaded',timeout:120000});await ready(p);
 await p.evaluate(async()=>{await goSearch();await setSupplementMode('aflp',{persist:false,rerender:false,silent:true,origin:'qa'});});
 const ch=p.locator('#screen-search .documentary-view-status.show .documentary-view-status-btn').filter({hasText:'Changer'});await ch.focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.getElementById('documentary-view-overlay').classList.contains('show'));await p.keyboard.press('Escape');await sl(80);
 const esc=await p.evaluate(()=>({tag:document.activeElement.tagName,text:document.activeElement.textContent.trim(),cls:document.activeElement.className}));O.details.escape=esc;O.checks.e12_escape=esc.text==='Changer';
 await ch.focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.getElementById('documentary-view-overlay').classList.contains('show'));const normal=p.locator('#documentary-view-overlay [data-documentary-choice="enriched"]');await normal.focus();await p.keyboard.press('Enter');await sl(600);
 const choice=await p.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,mode:supplementMode,visible:document.activeElement.getClientRects().length>0}));O.details.choice=choice;O.checks.e12_choice=choice.mode==='enriched'&&choice.tag!=='BODY'&&choice.visible;
 await p.evaluate(()=>{setSearchIntentMode('words',{rerun:false,persist:false});const i=document.getElementById('search-input');i.value="Jésus explique que l'âme doit abandonner sa volonté humaine pour vivre entièrement dans la volonté divine";onSearchInput('words');});
 await p.evaluate(()=>runSearch());await p.waitForFunction(()=>!searchBusyGeneration,null,{timeout:120000});await sl(400);
 const before=await p.evaluate(()=>({cards:document.querySelectorAll('#search-results .result-card').length,meta:document.getElementById('search-meta').innerText,button:[...document.querySelectorAll('#search-results button')].find(b=>b.textContent.includes('Voir les résultats élargis'))?.textContent||null,lane:searchResultLane,expanded:searchPartialExpanded,partial:Number(searchLastPayload?.matchCounts?.partial||0)}));O.details.e20_before=before;
 O.checks.e20_truthful=before.cards===0&&before.partial>0&&!/^0 résultat/.test(before.meta)&&/correspondance/.test(before.meta)&&before.button==='Voir les résultats élargis';
 await p.getByRole('button',{name:'Voir les résultats élargis'}).click();await p.waitForFunction(()=>!searchBusyGeneration,null,{timeout:120000});await sl(300);
 const after=await p.evaluate(()=>({cards:document.querySelectorAll('#search-results .result-card').length,lane:searchResultLane,expanded:searchPartialExpanded,meta:document.getElementById('search-meta').innerText}));O.details.e20_after=after;O.checks.e20_expand=after.cards>0&&after.lane==='partial'&&after.expanded===true;
 await p.evaluate(()=>renderSearchV2Results({results:[],metadata:[],matchCounts:{exact:0,words:2,partial:7},foundation:{lane:'exact',mode:supplementMode,page:1,pageCount:1,metadataPage:1,metadataPageCount:1},totalMatches:0,totalBodyMatches:9,metadataTotalMatches:0,parsed:{lexical:'test'},suggestions:[],near:{eligible:false,results:[]}},'test'));
 const boundary=await p.evaluate(()=>({meta:document.getElementById('search-meta').innerText,button:[...document.querySelectorAll('#search-results button')].some(b=>b.textContent.includes('Voir les résultats élargis'))}));
 O.details.e20_boundary=boundary;O.checks.e20_no_false_partial_disclosure=!/Aucun passage avec tous les termes/.test(boundary.meta)&&boundary.button===false;
 O.checks.no_errors=O.errors.length===0;O.overall=Object.values(O.checks).every(Boolean)?'PASS':'FAIL';
}catch(e){O.errors.push(String(e&&e.stack||e));O.overall='HARNESS_ERROR'}finally{await c.close();await b.close()}fs.writeFileSync('wip-e12-e20.json',JSON.stringify(O,null,2)+'\n');console.log(JSON.stringify(O,null,2));if(O.overall!=='PASS')process.exitCode=1})();