const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const URL='https://louisriv26.github.io/App-Test/ldc-v134-r7-governed-r6/';
const INDEX_SHA=crypto.createHash('sha256').update(fs.readFileSync(path.join(process.cwd(),'ldc-v134-r7-governed-r6','index.html'))).digest('hex');
const PROFILE=path.join(process.cwd(),'.ldc-r6-v134-profile');
const out={generated_at:new Date().toISOString(),candidate:'LDC v134/R7',overall:'UNKNOWN'};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function sw(page){return page.evaluate(async()=>{const reg=await Promise.race([navigator.serviceWorker.ready,new Promise((_,rej)=>setTimeout(()=>rej(new Error('sw_timeout')),25000))]);return{active:reg.active&&reg.active.scriptURL,scope:reg.scope,controller:!!navigator.serviceWorker.controller};});}
async function openOnline(){
 fs.rmSync(PROFILE,{recursive:true,force:true});
 const c=await chromium.launchPersistentContext(PROFILE,{headless:true,serviceWorkers:'allow',viewport:{width:1180,height:850}});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));
 const r=await p.goto(URL,{waitUntil:'domcontentloaded',timeout:90000}),body=Buffer.from(await r.body());
 out.navigation={status:r.status(),sha256:sha(body),exact:sha(body)===INDEX_SHA};
 await sleep(1200);let s=await sw(p);if(!s.controller){await p.reload({waitUntil:'domcontentloaded',timeout:90000});await sleep(900);s=await sw(p);}out.sw=s;
 out.identity=await p.evaluate(()=>({app:typeof APP_VERSION!=='undefined'?APP_VERSION:null,pub:typeof PUBLIC_VERSION!=='undefined'?PUBLIC_VERSION:null,swExpected:typeof SW_CACHE_VERSION!=='undefined'?SW_CACHE_VERSION:null}));
 out.d04=await p.evaluate(()=>{document.documentElement.setAttribute('data-theme','dark');const e=document.getElementById('resume-reading-btn'),cs=getComputedStyle(e);const parse=s=>{const m=String(s).match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?[+m[1],+m[2],+m[3]]:null};const lum=a=>a.map(v=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)}).reduce((z,v,i)=>z+v*[.2126,.7152,.0722][i],0),fg=parse(cs.color),bg=parse(cs.backgroundColor),a=lum(fg),b=lum(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);return{color:cs.color,background:cs.backgroundColor,ratio,pass:ratio>=4.5};});
 out.backup_roundtrip=await p.evaluate(async()=>{await setThemePreference('dark');const env=await collectUserDataEnvelope();await setThemePreference('light');const prepared=await prepareBackupEnvelopeForImport(env),bytes=new TextEncoder().encode(JSON.stringify(prepared.env)).length,validation=await validateBackupEnvelope(prepared.env,bytes);if(!validation.ok)return{pass:false,errors:validation.errors};pendingBackupImport={kind:'legacy-json',env:prepared.env,validation,fileName:'r6-v134-memory.json',migrationSummary:prepared.summary};await confirmImportBackup();const theme=await dbGet('settings','theme').catch(()=>null);return{pass:!!theme&&theme.val==='dark',theme:theme&&theme.val,warnings:validation.warnings};});
 await p.evaluate(()=>{window.__r6D11=[];const live=document.getElementById('offline-at-status'),toast=document.getElementById('toast');const take=()=>window.__r6D11.push({at:Date.now(),live:live&&live.textContent||'',toast:toast&&toast.textContent||'',state:typeof offlineUiState!=='undefined'?offlineUiState.state:null,message:typeof offlineUiState!=='undefined'?offlineUiState.message:null});if(live)new MutationObserver(take).observe(live,{subtree:true,childList:true,characterData:true});if(toast)new MutationObserver(take).observe(toast,{subtree:true,childList:true,characterData:true,attributes:true});take();});
 try{await p.waitForFunction(()=>typeof offlineUiState!=='undefined'&&!['CHECKING','DOWNLOADING'].includes(offlineUiState.state),{timeout:45000});}catch(_){}
 await p.evaluate(()=>startOfflinePreparation());
 try{await p.waitForFunction(()=>typeof offlineUiState!=='undefined'&&['READY','ERROR','PARTIAL','CANCELLED'].includes(offlineUiState.state),{timeout:900000,polling:1000});}catch(e){out.prepare_wait_error=String(e);}
 await sleep(1000);
 out.d11=await p.evaluate(async()=>{const saved=await dbGet('settings','offline_completion').catch(()=>null);return{state:offlineUiState.state,message:offlineUiState.message,completed:offlineUiState.completed,total:offlineUiState.total,failed:(offlineUiState.failed||[]).length,total_bytes:offlineUiState.total_bytes,label:document.getElementById('offline-state-label')?.textContent||'',live:document.getElementById('offline-at-status')?.textContent||'',toast:document.getElementById('toast')?.textContent||'',saved:saved&&(saved.val||saved.value),events:window.__r6D11||[]};});
 out.d11.pass=out.d11.state==='READY'&&out.d11.failed===0&&out.d11.total===204&&out.d11.completed===204&&/Prêt hors ligne/.test(out.d11.label)&&out.d11.saved&&out.d11.saved.state==='READY'&&out.d11.events.some(x=>/terminée/i.test(x.live||''))&&out.d11.events.some(x=>/prêt hors ligne/i.test(x.toast||''));
 out.online_errors=errors;await c.close();
}
async function openOffline(){
 const c=await chromium.launchPersistentContext(PROFILE,{headless:true,serviceWorkers:'allow',viewport:{width:1180,height:850}});await c.setOffline(true);
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));let nav=true,nav_error=null;try{await p.goto(URL,{waitUntil:'domcontentloaded',timeout:45000});}catch(e){nav=false;nav_error=String(e)}await sleep(1800);
 out.cold=await p.evaluate(async()=>{const off=await dbGet('settings','offline_completion').catch(()=>null);async function f(u){try{const r=await fetch(u,{cache:'no-store'}),b=await r.arrayBuffer();return{ok:r.ok,status:r.status,bytes:b.byteLength}}catch(e){return{ok:false,error:String(e)}}}return{app:typeof APP_VERSION!=='undefined'?APP_VERSION:null,pub:typeof PUBLIC_VERSION!=='undefined'?PUBLIC_VERSION:null,ui:typeof offlineUiState!=='undefined'?offlineUiState.state:null,saved:off&&(off.val||off.value),volume36:await f('./corpus/volume_36.json'),searchIndex:await f('./corpus/search_v2_index.json')};});
 out.cold.nav_ok=nav;out.cold.nav_error=nav_error;out.cold.errors=errors;out.cold.pass=nav&&out.cold.pub==='134'&&out.cold.saved&&out.cold.saved.state==='READY'&&out.cold.volume36.ok&&out.cold.searchIndex.ok;await c.close();
}
(async()=>{try{await openOnline();if(out.d11&&out.d11.state==='ERROR'&&/stockage insuffisant|storage|quota/i.test(out.d11.message||'')){out.overall='BLOCKED_ENVIRONMENT';}else{await openOffline();out.overall=out.navigation.exact&&out.sw.active&&out.identity.app==='v2.19.134-R1B-UX-ACCESS-R7'&&out.identity.pub==='134'&&out.identity.swExpected==='ldc-v2.19.134-R1B-ux-access-r7'&&out.d04.pass&&out.backup_roundtrip.pass&&out.d11.pass&&out.cold.pass?'PASS':'FAIL';}}catch(e){out.overall='HARNESS_ERROR';out.error=String(e&&e.stack||e);}fs.writeFileSync('governed-r6-ldc-v134-results.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({overall:out.overall,d04:out.d04,d11:out.d11&&{state:out.d11.state,completed:out.d11.completed,total:out.d11.total,failed:out.d11.failed,pass:out.d11.pass},cold:out.cold&&{pass:out.cold.pass,volume36:out.cold.volume36,searchIndex:out.cold.searchIndex}},null,2));if(out.overall==='FAIL'||out.overall==='HARNESS_ERROR')process.exitCode=1;})();